apiVersion: v1
kind: Service
metadata:
  name: zrwio-webserver
  labels:
    k8s-app: zrwio-webserver
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: zrwio-webserver
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zrwio-webserver
spec:
  replicas: 1
  selector:
    k8s-app: zrwio-webserver
  template:
    metadata:
      labels:
        k8s-app: zrwio-webserver
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: zrwio-webserver
        image: webdevops/php-nginx:latest
        env:
        - name: WEB_DOCUMENT_ROOT
          value: "/var/www/zrw.io"
        - name: WEB_DOCUMENT_INDEX
          value: "index.html"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www
          name: zrwio-git-volume
      volumes:
      - name: zrwio-git-volume
        gitRepo:
          repository: "https://github.com/rwejlgaard/zrw.io.git"