apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-webdis
spec:
  replicas: 1
  selector:
    k8s-app: redis-webdis
  template:
    metadata:
      labels:
        k8s-app: redis-webdis
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: redis-webdis
        image: robtec/webdis
        ports:
        - containerPort: 80